name: Update posts.json

permissions:
  contents: write

on:
  push:
    paths:
      - 'posts/*.md'

jobs:
  update-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate posts.json
        run: |
          echo "[" > posts.json
          ls posts/*.md | sed 's|posts/||' | sed 's|^|  "|;s|$|"|' | paste -sd, - >> posts.json
          echo "]" >> posts.json

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add posts.json
          git commit -m "Auto-update posts.json" || echo "No changes"
          git push
